// <auto-generated />
using Comrade.Persistence.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Comrade.Persistence.Migrations
{
    [DbContext(typeof(ComradeContext))]
    partial class ComradeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Comrade.Domain.Models.Airplane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("AIRP_SQ_AIRPLANE")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("AIRP_TX_CODIGO");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("AIRP_TX_MODELO");

                    b.Property<int>("PassengerQuantity")
                        .HasColumnType("int")
                        .HasColumnName("AIRP_QT_PASSAGEIRO");

                    b.Property<string>("RegisterDate")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("AIRP_DT_REGISTRO");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_UN_AIRP_TX_CODIGO");

                    b.ToTable("AIRP_AIRPLANE");
                });

            modelBuilder.Entity("Comrade.Domain.Models.SystemUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("USSI_SQ_USUARIO_SISTEMA")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("USSI_TX_EMAIL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("USSI_TX_NOME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(1023)
                        .HasColumnType("varchar")
                        .HasColumnName("USSI_PW_SENHA");

                    b.Property<string>("RegisterDate")
                        .HasColumnType("varchar")
                        .HasColumnName("USSI_DT_REGISTRO");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("USSI_TX_MATRICULA");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_UN_USSI_TX_EMAIL");

                    b.HasIndex("Registration")
                        .IsUnique()
                        .HasDatabaseName("IX_UN_USSI_TX_MATRICULA");

                    b.ToTable("USSI_USUARIO_SISTEMA");
                });
#pragma warning restore 612, 618
        }
    }
}
